# Generated by Django 4.1.4 on 2023-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
