# Generated by Django 4.1.4 on 2023-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tag_status_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='tags',
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
